<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3lib"
 *
 * Auto generated by Extension Builder 2016-11-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'T3lib',
	'description' => 'Our library for typo3
- ViewHelpers
- TypoScript Settings
- a.s.o.',
	'category' => 'misc',
	'author' => 'André Sünnemann',
	'author_email' => 'a.suennemann@edv-peuker.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'autoload' => array(
		'psr-4' => array('ESP\\T3lib\\' => 'Classes')
	),
);